# Generated by Django 2.2.6 on 2019-11-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='modify',
            new_name='modified',
        ),
    ]
